Extended documentation of ghost
cburstedde/p4est pull request #317
Opened 2024-09-18 13:25 UTC by tim-griesbach

# Extended documentation of ghost

This PR extends and adds documentation on the ghost layer in p4est. The concrete changes are
- a new Doxygen page on the ghost layer that gives a general introduction (in parts based on https://p4est.org/tutorial-ghost.html),
- add and reference existing examples for ghost,
- fix all Doxygen warnings in `p{4,8}est_ghost.h` and
- extend the documentation on piggies in the `p{4,8}est_quadrant_data` and clarify the role of the piggies.

2024-09-18 13:59 UTC, efaulhaber requested changes
Thanks, LGMT! Just one typo.

2024-09-18 13:59 UTC, efaulhaber commented on doc/doxygen/ghost.dox
> + * The second and last required parameter to construct a ghost layer is is a
```suggestion
 * The second and last required parameter to construct a ghost layer is a
```

2024-09-18 14:27 UTC, tim-griesbach commented on doc/doxygen/ghost.dox
> + * The second and last required parameter to construct a ghost layer is is a
Thank you!

2024-09-19 08:05 UTC, cburstedde commented
Thanks, looks great. I like the extra doc page a lot, and thanks for going after the warnings.

2024-09-19 08:10 UTC, merged